"""empty message

Revision ID: 47a29340e82f
Revises: 9793811d5232
Create Date: 2016-05-26 23:24:08.472534

"""

# revision identifiers, used by Alembic.
revision = '47a29340e82f'
down_revision = '9793811d5232'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'chats_name_key', 'chats', type_='unique')
    op.drop_column('chats', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'chats_name_key', 'chats', ['name'])
    ### end Alembic commands ###
