"""empty message

Revision ID: bb93e9c2dc54
Revises: 47a29340e82f
Create Date: 2016-05-26 23:35:07.793708

"""

# revision identifiers, used by Alembic.
revision = 'bb93e9c2dc54'
down_revision = '47a29340e82f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'chats', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'name')
    ### end Alembic commands ###
